# Generated by Django 4.2 on 2023-04-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.PositiveIntegerField(),
        ),
    ]
